language: php
sudo: false

services:
  - mysql

before_install:
  - composer self-update
  - git clone https://github.com/llaull/AppBundleX.git
  - git clone https://github.com/llaull/domotikBundle.git
  - mv  -v src/AppBundleX/* src/AppBundle/
  - mv  -v src/domotikBundle/* src/Domotique/

install:
  - composer install

before_script:
  - mysql -e 'create database test;'
  - php app/console doctrine:schema:create -n
  - php app/console doctrine:fixtures:load -n
  - php app/console doctrine:schema:create -n --env test
  - php app/console doctrine:fixtures:load -n --env test
  - php app/console server:start

script:
#  - php bin/codecept run