language: php
sudo: false

services:
  - mysql

before_install:
  - composer self-update
  - cd src
  - dir
  - git clone https://github.com/llaull/AppBundleX.git
  - git clone https://github.com/llaull/domotikBundle.git
  - mv  -v AppBundleX/* AppBundle/
  - mv  -v domotikBundle/* Domotique/
  - cd AppBundle
  - dir
  - cd ../
  - cd AppBundleX
  - dir
  - cd ../
  - dir
  - cd ../
  - mysql -e 'create database test;'

install:
  - composer install

before_script:
  - mysql -e 'create database test;'
  - php app/console doctrine:schema:create -n
  - php app/console doctrine:fixtures:load -n
  - php app/console doctrine:schema:create -n --env test
  - php app/console doctrine:fixtures:load -n --env test
  - php app/console server:start

script:
#  - php bin/codecept run

# script: phpunit --coverage-text --coverage-clover=coverage.clover 

# after_script: 
  # - wget https://scrutinizer-ci.com/ocular.phar 
  # - php ocular.phar code-coverage:upload --format=php-clover coverage.clover 

# cache: 
  # directories: 
    # - $COMPOSER_CACHE_DIR - See more at: http://frankneff.ch/quality-assurance/2014/04/19/use-travis-build-matrix-to-test-against-multiple-symfony-versions/#sthash.Gdl7N7CG.dpuf