language: php

php:
  - 5.6

services:
  - mysql

before_script:
  - composer self-update
  - mysql -e 'create database test;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --dev --no-interaction
  - php bin/console doctrine:schema:update --force
  - php bin/console fos:user:create test test test --super-admin
  - php bin/console doctrine:migrations:migrate -n
  - php bin/console cache:clear

script:
  - phpunit -c app/


notifications:
  email:
    - laurent@llovem.eu