language: php
sudo: false

services:
  - mysql

before_install:
  - composer self-update
  - cd src
  - dir
  - git clone https://github.com/llaull/AppBundleX.git
  - git clone https://github.com/llaull/domotikBundle.git
  - mv  -v AppBundleX/* AppBundle/
  - mv  -v domotikBundle/* Domotique/
  - cd ../
  - mysql -e 'create database symfony;'


install:
  - composer install

before_script:
  - mysql -e 'create database test;'
  - php app/console doctrine:schema:create
  - php bin/console fos:user:create test test test --super-admin

script:
#  - php vendor/phpunit/phpunit/phpunit -c app/ doublon
  - php vendor/phpunit/phpunit/phpunit -c app/ --coverage-text --coverage-clover coverage.xml -c app
  - dir


after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

# cache: 
  # directories: 
    # - $COMPOSER_CACHE_DIR - See more at: http://frankneff.ch/quality-assurance/2014/04/19/use-travis-build-matrix-to-test-against-multiple-symfony-versions/#sthash.Gdl7N7CG.dpuf