language: php
sudo: false

before_install:
  - composer self-update
  - cd src
  - git clone https://github.com/llaull/AppBundleX.git
  - git clone https://github.com/llaull/domotikBundle.git
  - ../

install:
  - composer install

before_script:
  - php app/console doctrine:schema:create -n
  - php app/console doctrine:fixtures:load -n
  - php app/console doctrine:schema:create -n --env test
  - php app/console doctrine:fixtures:load -n --env test
  - php app/console server:start

script:
#  - php bin/codecept run