frond_office_homepage:
    resource: "@FrondOfficeBundle/Resources/config/routing.yml"
    prefix:   /

back_office_homepage:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"