frond_office_homepage:
    resource: "@FrondOfficeBundle/Resources/config/routing.yml"
    prefix:   /

back_office_homepage:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

domotique_domobox:
    resource: "@DomotiqueDomoboxBundle/Resources/config/routing.yml"
    prefix:   /

domotique_reseau:
    resource: "@DomotiqueReseauBundle/Resources/config/routing.yml"
    prefix:   /

# add by composer
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# WYSIWYG
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
